#! /bin/bash
#detección de SO 
if type -t wevtutil &> /dev/null 
then 
    OS=MSWin 
elif type -t scutil &> /dev/null 
then 
    OS=macOS 
else 
    OS=Linux
fi
echo $OS
#termina detección de SO
#escaneo de red local
function is_alive_ping() { 
  ping -c 1 $1 > /dev/null 2>&1 
  [ $? -eq 0 ] && echo "Node with IP: $i is up." 


host=$1
firstport=10
lastport=25
#Funcion para escanear puertos
for ((counter=$firstport; counter<=$lastport; counter++)) 
do 
    (echo >/dev/tcp/$host/$counter) > /dev/null 2>&1 && echo "$counter open" 
done 
}


for i in 192.168.1.{1..255} 
do 
  is_alive_ping $i & disown 
done
#termina escaneo de red local
